#!/bin/sh

# Rank ; Country ; Confirmed Cases ; Recovered ; Deaths ; Active ; Mortality Rate ; Recovery Rate ; 1 Day increase ; 1 Week increase

[ "$(stat -c %y ~/.cache/corona-world 2>/dev/null | cut -d' ' -f1)" != "$(date '+%Y-%m-%d')" ] &&
    curl -s https://corona-stats.online > ~/.cache/corona-world

[ "$(stat -c %y ~/.cache/corona-uk 2>/dev/null | cut -d' ' -f1)" != "$(date '+%Y-%m-%d')" ] &&
    curl -s https://corona-stats.online/uk > ~/.cache/corona-uk

echo $(grep 'World' ~/.cache/corona-world | head -1)$(grep 'United Kingdom' ~/.cache/corona-uk | tail -1) |
    sed "s/\s*//g ; s/║║/;/g ; s/║//g ; s/│/;/g ; s/▲//g ; s/\x1b[[0-9;]*m//g" |
    awk -F';' '{print "  :   " $3 "   " $4 " (" $8 "%)   " $5 " (" $7 "%)   " $6 " (" $9 "  ) (" $10 "  ) |   :   " $12 "   " $13 " (" $17 "%)   " $14 " (" $16 "%)   " $15 " (" $18 "  ) (" $19 "  )" }'
